# --- Main Colors ---
background            #19120c
foreground            #efe0d6
cursor                #efe0d6
cursor_text_color     #19120c

selection_background  #5a422e
selection_foreground  #ffdcc3

url_color             #c5cb96

# --- ANSI Colors ---
color0                #19120c
color1                #ffb4ab
color2                #c5cb96
color3                #e3c0a6
color4                #ffb77d
color5                #c5cb96
color6                #e3c0a6
color7                #efe0d6

color8                #51443b
color9                #93000a
color10               #454a21
color11               #5a422e
color12               #6c3a07
color13               #5a422e
color14               #454a21
color15               #d6c3b6

# --- Starship Prompt Bubbles ---
color255              #6c3a07
color254              #ffb77d
color253              #5a422e
color252              #e3c0a6
color251              #454a21
color250              #c5cb96
color249              #93000a
color248              #ffb4ab

color232              #ffdcc3
color233              #4d2600
color234              #ffdcc3
color235              #422c1a
color236              #e1e7b0
color237              #2e330d
color238              #ffdad6
color239              #690005
color240              #ffdcc3

# Matched with unthemed light/dark
color243              #ffb77d
color244              #ffb4ab
color245              #51443b

# --- UI Elements ---
active_tab_foreground   #4d2600
active_tab_background   #ffb77d
inactive_tab_foreground #ffdcc3
inactive_tab_background #6c3a07

active_border_color     #ffb77d
inactive_border_color   #9e8e82

# --- Marks ---
mark1_foreground        #2f1500
mark1_background        #ffdcc3
mark2_foreground        #2a1707
mark2_background        #ffdcc3
mark3_foreground        #191e00
mark3_background        #e1e7b0
