# --- Main Colors ---
background            #0f1512
foreground            #dee4df
cursor                #dee4df
cursor_text_color     #0f1512

selection_background  #344c43
selection_foreground  #cee9dc

url_color             #a7cce1

# --- ANSI Colors ---
color0                #0f1512
color1                #ffb4ab
color2                #a7cce1
color3                #b2ccc1
color4                #88d6ba
color5                #a7cce1
color6                #b2ccc1
color7                #dee4df

color8                #3f4944
color9                #93000a
color10               #274b5d
color11               #344c43
color12               #00513e
color13               #344c43
color14               #274b5d
color15               #bfc9c3

# --- Starship Prompt Bubbles ---
color255              #00513e
color254              #88d6ba
color253              #344c43
color252              #b2ccc1
color251              #274b5d
color250              #a7cce1
color249              #93000a
color248              #ffb4ab

color232              #a4f2d5
color233              #00382a
color234              #cee9dc
color235              #1e352d
color236              #c3e8fe
color237              #0c3445
color238              #ffdad6
color239              #690005
color240              #a4f2d5

# Matched with unthemed light/dark
color243              #88d6ba
color244              #ffb4ab
color245              #3f4944

# --- UI Elements ---
active_tab_foreground   #00382a
active_tab_background   #88d6ba
inactive_tab_foreground #a4f2d5
inactive_tab_background #00513e

active_border_color     #88d6ba
inactive_border_color   #89938e

# --- Marks ---
mark1_foreground        #002117
mark1_background        #a4f2d5
mark2_foreground        #082018
mark2_background        #cee9dc
mark3_foreground        #001e2b
mark3_background        #c3e8fe
