[config]


[templates.rofi]
input_path = './templates/rofi.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.hyprland]
input_path = './templates/hyprland-colors.lua'
output_path = '~/.config/hypr/colors.lua'

[templates.firefox-website-colors]
input_path = "./templates/firefox-colors.css"
output_path = "~/.config/mozilla/firefox/g9a9crkc.default-release/chrome/colors.css"

[templates.quickshell]
input_path = './templates/quickshell-colors.json'
output_path = '~/.local/state/quickshell/generated/colors.json'

[templates.kitty]
input_path = './templates/kitty-colors.conf'
output_path = '~/.config/kitty/themes/Matugen.conf'
post_hook = "kitty +kitten themes --reload-in=all Matugen"

[templates.iisddmtheme]
input_path = '~/.config/ii-sddm-theme/SddmColors.qml'
output_path = '~/.config/ii-sddm-theme/Colors.qml'
post_hook = 'sudo ~/.config/ii-sddm-theme/sddm-theme-apply.sh &'

[templates.dunst]
input_path = './templates/dunstrc-colors'
output_path = '~/.config/dunst/dunstrc'
post_hook = 'dunstctl reload'
