[General]
bld="h5jBn/uE/GyK8l6L0+PFCA==|w8ZjXG/NhMtOYoptAjfzAc3uDzxWrGY2hd8BHXHpuvWexAnNdfm9KQLJQbhvHOWvLSzY+87PpbFqNzNHYqeSf1TtCCj+ow1CZVjVE8Y5J9LUrFnSHcGm8n9DjSi15f4E7GKeNax63b0LR4tE00PVsCY2cIbtDpF7n4AOYmyjTXAb/QWZNasLhfXrTON6H0pPyVft1LoqdUIQDw3Ru4jHA06qpa90H8YeCd3BY+bDwQ0xp7Q85/OI4yCR6+QIf3nweq+poQ=="

[Preferences]
Subscriptions\subsReadOnlyUserAgent=false
TunnelSettings\Muxing\muxingTcpConcurrency=8
TunnelSettings\Muxing\muxingXudpConcurrency=8
TunnelSettings\Noises\noisesSchemaV2=true
TunnelSettings\Routing\geoFilesUserAgent=firefox-win
TunnelSettings\Routing\selectedRoutingRule=@Invalid()
TunnelSettings\Routing\useRouting=@Invalid()
Updates\lastTimeCheckedForUpdate=1788777197
lastServer=1859406435
lastServerGuid=d8f01f82-4045-45fa-bdfe-6c1854f3f5d6
lastServerHost=
lastServerName=Европа ⚡
lastServerPort=
lastSubscription=-854735614
mode=Dark
screenIndex=0
windowHeight=996
windowVisibility=2
windowWidth=1876
windowX=22
windowY=62

[Vacancy]
bannerShownCount=2
