[General]
bld="0J7h19MKAlz7ddR1rTtGhw==|w8Z5SGrYkYQDYopgAjfzAd/rHStCuil0gNgEVH/n8PyPxBHQafXqZB/RTbZhX+aqPD3bocOIp7MmcDMDIb+DZ0vsE37k4hIZZVjVCdI8Mseb4VbXF8nv/HEJjjaysr0G+2iSeuYrhP1NS5pMwh3Y9md1P8yxSMF5jsBDeWqySjYV81SfIudOlOT8QaF9DhZPzUqpl6pqLkUJDxuQu5HNDwP4pvg6EN4PBd2VOeDez0Rt46h79PCX9X6ArfkOZXnyZbKp0I8QZsknW/RC4omZ5a8z"

[Preferences]
Subscriptions\subsReadOnlyUserAgent=false
TunnelSettings\Muxing\muxingTcpConcurrency=8
TunnelSettings\Muxing\muxingXudpConcurrency=8
TunnelSettings\Noises\noisesSchemaV2=true
TunnelSettings\PerAppProxy\appList=@Variant(\0\0\0\b\0\0\0\x2\0\0\0\x12\0m\0\x61\0t\0\x63\0h\0M\0o\0\x64\0\x65\0\0\0\n\0\0\0\b\0p\0\x61\0t\0h\0\0\0\b\0p\0\x61\0t\0h\0\0\0\n\0\0\0h\0/\0h\0o\0m\0\x65\0/\0r\0\x65\0\x65\0\x61\0r\0m\0i\0n\0g\0/\0.\0l\0o\0\x63\0\x61\0l\0/\0s\0h\0\x61\0r\0\x65\0/\0S\0t\0\x65\0\x61\0m\0/\0u\0\x62\0u\0n\0t\0u\0\x31\0\x32\0_\0\x33\0\x32\0/\0s\0t\0\x65\0\x61\0m), @Variant(\0\0\0\b\0\0\0\x2\0\0\0\x12\0m\0\x61\0t\0\x63\0h\0M\0o\0\x64\0\x65\0\0\0\n\0\0\0\b\0p\0\x61\0t\0h\0\0\0\b\0p\0\x61\0t\0h\0\0\0\n\0\0\0\xba\0/\0h\0o\0m\0\x65\0/\0r\0\x65\0\x65\0\x61\0r\0m\0i\0n\0g\0/\0.\0l\0o\0\x63\0\x61\0l\0/\0s\0h\0\x61\0r\0\x65\0/\0S\0t\0\x65\0\x61\0m\0/\0s\0t\0\x65\0\x61\0m\0\x61\0p\0p\0s\0/\0\x63\0o\0m\0m\0o\0n\0/\0\x64\0o\0t\0\x61\0 \0\x32\0 \0\x62\0\x65\0t\0\x61\0/\0g\0\x61\0m\0\x65\0/\0\x62\0i\0n\0/\0l\0i\0n\0u\0x\0s\0t\0\x65\0\x61\0m\0r\0t\0\x36\0\x34\0/\0\x64\0o\0t\0\x61\0\x32)
TunnelSettings\PerAppProxy\enabled=true
TunnelSettings\PerAppProxy\mode=1
TunnelSettings\Routing\geoFilesUserAgent=firefox-win
TunnelSettings\Routing\selectedRoutingRule=@Invalid()
TunnelSettings\Routing\useRouting=@Invalid()
Updates\lastTimeCheckedForUpdate=1789391116
lastServer=288589972
lastServerGuid=6df356de-4337-4438-94f0-1a32e843d972
lastServerHost=nl8.sky-vault.top
lastServerName=Европа ⚡
lastServerPort=443
lastSubscription=310158284
mode=Dark
screenIndex=0
windowHeight=996
windowVisibility=2
windowWidth=1876
windowX=22
windowY=62

[Vacancy]
bannerShownCount=2
