[General]
bld="YPLwGNw/P1FjMlsSMdiURw==|w8ZqXHvfhchOYoptAjfzAc3uD3VHuWB9xMIKBDCu6PuQhgiSbfbqZl7OFvpjHOWvfHWY5NTWpfQ/dGNDZ/XONUn6HXL84gMALhecQ456IMaYq1TPH4TotzNA32/y76UFrWLdYekny7cHBshU1R3GqmtiK8DvH9Ij3MYMfnWoSSFD8RWDOqtByKfzVOhoHwUCxVamm/M5LxAWQArOv5TNDwHnu/g6EMUKDJaEdvPBygkytfVt+bPduCyYtfIcZTa/Zrbll49UNMU2RPAVoIOY468z"

[Preferences]
Subscriptions\subsReadOnlyUserAgent=false
TunnelSettings\Muxing\muxingTcpConcurrency=8
TunnelSettings\Muxing\muxingXudpConcurrency=8
TunnelSettings\Noises\noisesSchemaV2=true
TunnelSettings\PerAppProxy\appList=@Variant(\0\0\0\b\0\0\0\x2\0\0\0\x12\0m\0\x61\0t\0\x63\0h\0M\0o\0\x64\0\x65\0\0\0\n\0\0\0\b\0p\0\x61\0t\0h\0\0\0\b\0p\0\x61\0t\0h\0\0\0\n\0\0\0h\0/\0h\0o\0m\0\x65\0/\0r\0\x65\0\x65\0\x61\0r\0m\0i\0n\0g\0/\0.\0l\0o\0\x63\0\x61\0l\0/\0s\0h\0\x61\0r\0\x65\0/\0S\0t\0\x65\0\x61\0m\0/\0u\0\x62\0u\0n\0t\0u\0\x31\0\x32\0_\0\x33\0\x32\0/\0s\0t\0\x65\0\x61\0m), @Variant(\0\0\0\b\0\0\0\x2\0\0\0\x12\0m\0\x61\0t\0\x63\0h\0M\0o\0\x64\0\x65\0\0\0\n\0\0\0\b\0p\0\x61\0t\0h\0\0\0\b\0p\0\x61\0t\0h\0\0\0\n\0\0\0\xba\0/\0h\0o\0m\0\x65\0/\0r\0\x65\0\x65\0\x61\0r\0m\0i\0n\0g\0/\0.\0l\0o\0\x63\0\x61\0l\0/\0s\0h\0\x61\0r\0\x65\0/\0S\0t\0\x65\0\x61\0m\0/\0s\0t\0\x65\0\x61\0m\0\x61\0p\0p\0s\0/\0\x63\0o\0m\0m\0o\0n\0/\0\x64\0o\0t\0\x61\0 \0\x32\0 \0\x62\0\x65\0t\0\x61\0/\0g\0\x61\0m\0\x65\0/\0\x62\0i\0n\0/\0l\0i\0n\0u\0x\0s\0t\0\x65\0\x61\0m\0r\0t\0\x36\0\x34\0/\0\x64\0o\0t\0\x61\0\x32)
TunnelSettings\PerAppProxy\enabled=true
TunnelSettings\PerAppProxy\mode=1
TunnelSettings\Routing\geoFilesUserAgent=firefox-win
TunnelSettings\Routing\selectedRoutingRule=@Invalid()
TunnelSettings\Routing\useRouting=@Invalid()
Updates\lastTimeCheckedForUpdate=1789391116
lastServer=-1073052009
lastServerGuid=f9312790-4fb8-4c0c-94ec-ed48fdbd1a68
lastServerHost=
lastServerName=Европа ⚡
lastServerPort=
lastSubscription=310158284
mode=Dark
screenIndex=0
windowHeight=996
windowVisibility=2
windowWidth=931
windowX=967
windowY=62

[Vacancy]
bannerShownCount=2
