# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#efe0d6"

# Title color for boxes
theme[title]="#ffb77d"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#e3c0a6"

# Background color of selected item in processes box
theme[selected_bg]="#ffb77d"

# Foreground color of selected item in processes box
theme[selected_fg]="#4d2600"

# Color of inactive/disabled text
theme[inactive_fg]="#d6c3b6"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#c5cb96"

# Cpu box outline color
theme[cpu_box]="#9e8e82"

# Memory/disks box outline color
theme[mem_box]="#9e8e82"

# Net up/down box outline color
theme[net_box]="#9e8e82"

# Processes box outline color
theme[proc_box]="#9e8e82"

# Box divider line and small boxes line color
theme[div_line]="#51443b"

# Temperature graph colors
theme[temp_start]="#e3c0a6"
theme[temp_mid]="#ffb77d"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#e3c0a6"
theme[cpu_mid]="#ffb77d"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#e3c0a6"
theme[free_mid]=""
theme[free_end]="#5a422e"

# Mem/Disk cached meter
theme[cached_start]="#c5cb96"
theme[cached_mid]=""
theme[cached_end]="#454a21"

# Mem/Disk available meter
theme[available_start]="#ffb77d"
theme[available_mid]=""
theme[available_end]="#6c3a07"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#e3c0a6"
theme[download_mid]="#ffb77d"
theme[download_end]="#c5cb96"

# Upload graph colors
theme[upload_start]="#e3c0a6"
theme[upload_mid]="#ffb77d"
theme[upload_end]="#c5cb96"
